import random

from chatterbot.logic import LogicAdapter
from chatterbot.conversation import Statement

class HowAreYouQ(LogicAdapter):
    def __init__(self, chatbot, **kwargs):
        super().__init__(chatbot, **kwargs)

    def can_process(self, statement):
        print("Checking if can process:", statement.text)
        questions = [
            "how are you",
            "how are you feeling today",
            "what's new with you",
            "how have you been lately",
            "how's everything going",
            "what's up",
            "how are things on your end",
            "how's your day been so far",
            "how are you holding up",
            "how's life treating you",
            "how's your day shaping up",
            "how are things going in your neck of the woods",
            "how are things in your corner of the universe",
            "how's your day treating you",
            "how's your week been",
            "how are you doing today",
            "how are you getting on",
            "how's your day panning out",
            "how's your mood today",
            "how are things going with you",
            "how's your energy today",
            "how's your health these days",
            "how are you feeling these days",
            "how's everything with you lately",
            "how's your spirit today",
            "how's your morale",
            "how's your vibe today",
            "how's your state of mind",
            "how's your frame of mind",
            "how's your outlook today",
            "how's your mental state",
            "how's your emotional state",
            "how's your headspace today",
            "how's your well-being",
            "how's your inner peace today",
            "how's your sense of balance",
            "how's your level of motivation",
            "how's your level of enthusiasm",
            "how's your level of energy today",
            "how's your level of positivity",
            "how are things looking for you",
            "how are things shaping up for you",
            "how's your day unfolding",
            "how's your day progressing",
            "how's your day rolling along",
            "how's your day shaping up so far",
            "how's your day turning out",
            "how's your day evolving",
            "how's your day progressing along",
            "how's your day moving along",
            "how's your day coming along",
            "how's your day unfolding so far",
            "how's your day shaping up thus far",
            "how's your day panning out thus far",
            "how's your day progressing thus far",
            "how's your day rolling along so far",
            "how's your day shaping up at this point",
            "how's your day turning out thus far",
            "how's your day evolving thus far",
            "how's your day moving along thus far",
            "how's your day coming along so far",
            "how's your day going so far",
            "how's your day so far",
            "how's your day been",
            "how's your day been treating you",
            "how's your day treated you thus far",
            "how's your day treating you up to now",
            "how's your day treated you up to this point",
            "how's your day treated you to this moment",
            "how's your day been going for you",
            "how's your day treating you so far",
            "how's your day treating you thus far",
            "how's your day treating you up to this point",
            "how's your day treating you up to now",
            "how's your day treating you to this moment",
            "how's your day going for you so far",
            "how's your day going for you up to this point",
            "how's your day going for you up to now",
            "how's your day going for you to this moment",
            "how's your day going for you thus far",
            "how's your day going for you at this point",
            "how's your day going for you at this moment",
            "how's your day going for you right now",
            "how's your day going for you currently",
            "how's your day going for you presently",
            "how's your day going for you today",
            "how's your day going for you this morning/afternoon/evening",
            "how's your day going for you at this time",
            "how's your day going for you this very moment",
            "how's your day going for you at the present moment",
            "how's your day going for you at this exact moment",
            "how's your day going for you right at this moment",
            "how's your day going for you right at this very moment",
            "how's your day going for you right at this present moment",
            "how's your day going for you right at this exact moment",
            "how's your day going for you right now at this very moment",
            "how's your day going for you right now at this present moment",
            "how's your day going for you right now at this exact moment",
            "how's your day going for you currently at this very moment",
            "how's your day going for you currently at this present moment"
        ]
        if any(question in statement.text.lower() for question in questions):
            return True
        else:
            return False

    def process(self, input_statement, additional_response_selection_parameters):
        print("Processing:", input_statement.text)
        responses = [
            "Not great, honestly.",
            "Could be better, to be honest.",
            "Having a rough day, unfortunately.",
            "Feeling a bit down, to be honest.",
            "Struggling a bit lately.",
            "Not the best, unfortunately.",
            "Rough patch lately.",
            "Feeling pretty low, to be honest.",
            "It's been tough, unfortunately.",
            "Not so good, thanks.",
            "Rough times lately.",
            "Could use a break, to be honest.",
            "Pretty lousy, thanks.",
            "Been better, unfortunately.",
            "Feeling pretty down, thanks.",
            "Could use a pick-me-up, honestly.",
            "Not the greatest, unfortunately.",
            "Just trying to get through it, thanks.",
            "It's been a struggle lately.",
            "Not great, thanks.",
            "Tough times lately.",
            "Could be worse, unfortunately.",
            "Just trying to push through it, thanks.",
            "Not the best day, thanks.",
            "Rough patch lately, thanks.",
            "Feeling overwhelmed lately.",
            "Could be better, to be honest.",
            "Having a bit of a tough time lately.",
            "Pretty rough, thanks.",
            "Not feeling so hot, unfortunately.",
            "Could be better, thanks.",
            "Tough day, thanks.",
            "Feeling pretty down, to be honest.",
            "Could use a break, thanks.",
            "Rough times, unfortunately.",
            "Just trying to cope, thanks.",
            "Could be worse, to be honest.",
            "Just taking it one day at a time, thanks.",
            "Feeling drained, unfortunately.",
            "Not the best, unfortunately.",
            "Just trying to hang in there, thanks.",
            "Feeling a bit under the weather, unfortunately.",
            "Could be better, thanks.",
            "Having a bit of a rough time, unfortunately.",
            "Pretty exhausted, thanks.",
            "Not feeling too great, unfortunately.",
            "Just struggling a bit lately, thanks.",
            "Feeling a bit off, to be honest.",
            "Not the best shape, unfortunately.",
            "Just not feeling it today, thanks.",
            "I'm doing great, thanks!",
            "Fantastic!",
            "Pretty good, all things considered.",
            "Doing well.",
            "Just peachy, thanks!",
            "Surviving the chaos.",
            "Couldn't be better.",
            "Hanging in there.",
            "Living the dream.",
            "Better than I deserve.",
            "Wonderful!",
            "Just splendid.",
            "So far, so good.",
            "Not bad at all.",
            "Pretty good.",
            "Feeling pretty decent.",
            "I'm doing okay.",
            "Doing well.",
            "Just fine, thank you.",
            "All good here.",
            "Better than yesterday.",
            "Doing fine.",
            "Hanging tough.",
            "Doing just fine.",
            "Doing alright.",
            "Pretty good, thanks.",
            "Just dandy.",
            "Great!",
            "I'm doing fine.",
            "Wonderful, thanks.",
            "Not bad.",
            "Doing good.",
            "Surviving.",
            "Doing well.",
            "Not too bad.",
            "Fantastic!",
            "Pretty good, thanks.",
            "Just fine, thanks.",
            "Doing great.",
            "Couldn't be better.",
            "Hanging in there.",
            "Living the dream.",
            "Better than I deserve.",
            "Not too shabby, thanks.",
            "Just fine, thank you.",
            "Doing alright, thanks.",
            "Wonderful, thanks.",
            "Just splendid, thanks.",
            "So far, so good.",
            "Doing well, thanks."
        ]
        response = random.choice(responses)
        return Statement(text=response)
